name: Build debug APK NEW

on:
  workflow_dispatch:
  push:
    branches:
      - 'jetpack_compose'
    paths-ignore:
      - 'README.md'
      - 'fastlane/**'
      - 'assets/**'
      - '.github/**/*.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
          cache: 'gradle'

      - name: Build debug APK
        run: |
          chmod +x ./gradlew  # Ensure gradlew has executable permission
          ./gradlew assembleDebug

      - name: Upload APK
        if: success()  # Upload artifact only if the build was successful
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/
